# Generated by Django 3.2.5 on 2022-03-30 19:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jotter',
            fields=[
                ('title', models.CharField(default='JotIT', max_length=200)),
                ('snippet', models.CharField(default='JotIT', max_length=200)),
                ('detail', models.TextField(default='JotIT')),
                ('important', models.BooleanField(default=False)),
                ('stamp', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.userprofile')),
            ],
        ),
    ]
