# Generated by Django 3.2.5 on 2022-03-30 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jotters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jotter',
            name='owner',
        ),
    ]
